/*  -------------------- Program Information --------------------
    Name Of Program: GuessingGame.java
    Date of Creation: 11/8/21
    Name of Author(s): Brady Butcher
    Version of Java: jdk-17
    Created with: Visual Studio Code
    Program Description: A game that will ask the user to try and guess an integer number between 1 and
        100. The number the user will be trying to guess is randomly generated by the
        computer. 
    -------------------- Program Information --------------------  */

import java.util.*;

public class GuessingGame {
    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in); //Initializes an input field

        /*Initialize Variables*/
        int count = 0;
        int high = 0;
        int low = 0;
        int guess;
        int max = 100;
        int min = 1;
        int rand = (int) (Math.random() * (max - min)) + min; //Generate a random number between min and max

        /*Asks for input between valid range*/
        System.out.println("Enter an integer between " + min + " and " + max);
        guess = scan.nextInt();

        /*If the guess isn't correct, keeps taking input and collecting data*/
        while (guess != rand) {
            if (guess < rand) {
                count++;
                low++;
                System.out.println("Too Low, Try again");
            } else {
                count++;
                high++;
                System.out.println("Too high, Try again");
            }
            guess = scan.nextInt();
            
        }
        /*Prints all collected data*/
        System.out.println("YOU WIN!");
        System.out.println("Correct number: " + rand);
        System.out.println("Total guesses: " + count);
        System.out.println("Number of high guesses: " + high);
        System.out.println("Number of low guesses: " + low);
    }
}